__author__ = 'indiano'

from autosklearn.pipeline.classification import SimpleClassificationPipeline

# The Ensemble of the best models discovered through Auto-Sklearn.

ensemble_choices = [(0.120000, SimpleClassificationPipeline(
    {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
     'classifier:adaboost:algorithm': 'SAMME', 'imputation:strategy': 'median',
     'categorical_encoding:one_hot_encoding:minimum_fraction': 0.2159437391641331, 'rescaling:__choice__': 'normalize',
     'classifier:adaboost:n_estimators': 330, 'classifier:adaboost:max_depth': 6, 'classifier:__choice__': 'adaboost',
     'preprocessor:__choice__': 'no_preprocessing',
     'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
     'classifier:adaboost:learning_rate': 0.24585586662439612},
    dataset_properties={
        'task': 1,
        'target_type': 'classification',
        'multilabel': False,
        'signed': False,
        'sparse': True,
        'multiclass': False})),
                    (0.100000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'imputation:strategy': 'mean',
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.004980497345831963,
                         'classifier:libsvm_svc:kernel': 'rbf', 'classifier:libsvm_svc:max_iter': -1,
                         'classifier:libsvm_svc:gamma': 0.08351549479967445, 'classifier:__choice__': 'libsvm_svc',
                         'preprocessor:__choice__': 'no_preprocessing', 'classifier:libsvm_svc:shrinking': 'True',
                         'classifier:libsvm_svc:C': 1255.9137433589424,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'classifier:libsvm_svc:tol': 0.00017919875199222518, 'rescaling:__choice__': 'normalize'},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.080000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'no_encoding', 'balancing:strategy': 'none',
                         'imputation:strategy': 'median', 'classifier:libsvm_svc:kernel': 'sigmoid',
                         'classifier:libsvm_svc:max_iter': -1, 'classifier:libsvm_svc:coef0': 0.9674382598902596,
                         'classifier:libsvm_svc:gamma': 0.00410145157284774, 'classifier:__choice__': 'libsvm_svc',
                         'preprocessor:__choice__': 'no_preprocessing', 'classifier:libsvm_svc:shrinking': 'True',
                         'classifier:libsvm_svc:C': 21465.94300620799,
                         'classifier:libsvm_svc:tol': 1.1994884859495466e-05, 'rescaling:__choice__': 'normalize'},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.080000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'no_encoding', 'balancing:strategy': 'none',
                         'classifier:adaboost:algorithm': 'SAMME', 'imputation:strategy': 'median',
                         'rescaling:__choice__': 'standardize',
                         'preprocessor:select_percentile_classification:score_func': 'chi2',
                         'classifier:adaboost:n_estimators': 360, 'classifier:adaboost:max_depth': 9,
                         'classifier:__choice__': 'adaboost',
                         'preprocessor:__choice__': 'select_percentile_classification',
                         'preprocessor:select_percentile_classification:percentile': 71.09953199485247,
                         'classifier:adaboost:learning_rate': 0.05930770715655241},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.060000, SimpleClassificationPipeline({'imputation:strategy': 'mean',
                                                             'categorical_encoding:one_hot_encoding:minimum_fraction': 0.02522176503208763,
                                                             'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                                                             'preprocessor:liblinear_svc_preprocessor:tol': 0.015420029551647053,
                                                             'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                                                             'classifier:__choice__': 'sgd',
                                                             'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                                                             'rescaling:__choice__': 'normalize',
                                                             'classifier:sgd:tol': 1.1212429965808787e-05,
                                                             'classifier:sgd:epsilon': 5.5590679369768634e-05,
                                                             'classifier:sgd:loss': 'modified_huber',
                                                             'categorical_encoding:__choice__': 'one_hot_encoding',
                                                             'balancing:strategy': 'weighting',
                                                             'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                                                             'classifier:sgd:fit_intercept': 'True',
                                                             'classifier:sgd:penalty': 'elasticnet',
                                                             'preprocessor:liblinear_svc_preprocessor:penalty': 'l1',
                                                             'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                                                             'classifier:sgd:l1_ratio': 0.4317556182779673,
                                                             'classifier:sgd:alpha': 1.0780644480287514e-05,
                                                             'classifier:sgd:average': 'False',
                                                             'classifier:sgd:learning_rate': 'optimal',
                                                             'preprocessor:liblinear_svc_preprocessor:C': 0.5770224171945469,
                                                             'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                                                             'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr'},
                                                            dataset_properties={
                                                                'task': 1,
                                                                'target_type': 'classification',
                                                                'multilabel': False,
                                                                'signed': False,
                                                                'sparse': True,
                                                                'multiclass': False})),
                    (0.060000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                         'imputation:strategy': 'median', 'classifier:passive_aggressive:average': 'True',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1',
                         'classifier:passive_aggressive:C': 0.004872725678770346,
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'passive_aggressive',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'preprocessor:liblinear_svc_preprocessor:C': 1.0,
                         'preprocessor:liblinear_svc_preprocessor:tol': 0.00010000000000000009,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'squared_hinge',
                         'classifier:passive_aggressive:tol': 1.3258146886140332e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.060000, SimpleClassificationPipeline(
                        {'classifier:liblinear_svc:dual': 'False', 'imputation:strategy': 'most_frequent',
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:tol': 3.9937571235550555e-05,
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'liblinear_svc',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'classifier:liblinear_svc:multi_class': 'ovr', 'classifier:liblinear_svc:intercept_scaling': 1,
                         'rescaling:__choice__': 'none', 'classifier:liblinear_svc:tol': 0.00010000000000000009,
                         'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1', 'classifier:liblinear_svc:C': 1.0,
                         'classifier:liblinear_svc:penalty': 'l2',
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'classifier:liblinear_svc:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:C': 0.4971515945303584,
                         'classifier:liblinear_svc:fit_intercept': 'True',
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr'},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.060000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'none',
                         'preprocessor:select_rates:score_func': 'chi2', 'classifier:adaboost:algorithm': 'SAMME',
                         'imputation:strategy': 'median',
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.2159437391641331,
                         'preprocessor:select_rates:mode': 'fpr', 'rescaling:__choice__': 'normalize',
                         'classifier:adaboost:n_estimators': 330, 'classifier:adaboost:max_depth': 9,
                         'classifier:__choice__': 'adaboost', 'preprocessor:__choice__': 'select_rates',
                         'preprocessor:select_rates:alpha': 0.06541751794377912,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'classifier:adaboost:learning_rate': 0.24585586662439612},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.040000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'classifier:adaboost:algorithm': 'SAMME.R', 'imputation:strategy': 'median',
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.19791786682642942,
                         'rescaling:__choice__': 'normalize', 'classifier:adaboost:n_estimators': 338,
                         'classifier:adaboost:max_depth': 2, 'classifier:__choice__': 'adaboost',
                         'preprocessor:__choice__': 'no_preprocessing',
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'classifier:adaboost:learning_rate': 1.494809921770793},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.040000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'none',
                         'imputation:strategy': 'mean', 'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'classifier:passive_aggressive:C': 1.6100833008493716,
                         'classifier:__choice__': 'passive_aggressive', 'preprocessor:__choice__': 'no_preprocessing',
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'squared_hinge',
                         'classifier:passive_aggressive:tol': 0.041995151184164234},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.040000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'imputation:strategy': 'median', 'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:select_percentile_classification:score_func': 'chi2',
                         'classifier:passive_aggressive:C': 5.741307665645392,
                         'classifier:__choice__': 'passive_aggressive',
                         'preprocessor:__choice__': 'select_percentile_classification',
                         'preprocessor:select_percentile_classification:percentile': 50.0,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.3232447497379641e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.040000, SimpleClassificationPipeline({'imputation:strategy': 'most_frequent',
                                                             'preprocessor:extra_trees_preproc_for_classification:criterion': 'gini',
                                                             'preprocessor:extra_trees_preproc_for_classification:min_impurity_decrease': 0.0,
                                                             'preprocessor:extra_trees_preproc_for_classification:max_leaf_nodes': 'None',
                                                             'classifier:__choice__': 'passive_aggressive',
                                                             'preprocessor:__choice__': 'extra_trees_preproc_for_classification',
                                                             'preprocessor:extra_trees_preproc_for_classification:min_samples_split': 2,
                                                             'preprocessor:extra_trees_preproc_for_classification:min_weight_fraction_leaf': 0.0,
                                                             'classifier:passive_aggressive:tol': 1.4434594858403402e-05,
                                                             'categorical_encoding:__choice__': 'one_hot_encoding',
                                                             'balancing:strategy': 'weighting',
                                                             'classifier:passive_aggressive:average': 'False',
                                                             'classifier:passive_aggressive:fit_intercept': 'True',
                                                             'classifier:passive_aggressive:C': 0.00016781524591321165,
                                                             'preprocessor:extra_trees_preproc_for_classification:bootstrap': 'False',
                                                             'preprocessor:extra_trees_preproc_for_classification:n_estimators': 100,
                                                             'preprocessor:extra_trees_preproc_for_classification:max_features': 0.5,
                                                             'preprocessor:extra_trees_preproc_for_classification:max_depth': 'None',
                                                             'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                                                             'preprocessor:extra_trees_preproc_for_classification:min_samples_leaf': 1,
                                                             'rescaling:__choice__': 'none',
                                                             'classifier:passive_aggressive:loss': 'squared_hinge'},
                                                            dataset_properties={
                                                                'task': 1,
                                                                'target_type': 'classification',
                                                                'multilabel': False,
                                                                'signed': False,
                                                                'sparse': True,
                                                                'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'classifier:__choice__': 'adaboost', 'preprocessor:__choice__': 'no_preprocessing',
                         'imputation:strategy': 'most_frequent', 'classifier:adaboost:algorithm': 'SAMME.R',
                         'classifier:adaboost:learning_rate': 1.6308355175471712,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'classifier:adaboost:n_estimators': 467, 'rescaling:__choice__': 'none',
                         'classifier:adaboost:max_depth': 6},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:select_rates:mode': 'fpr', 'imputation:strategy': 'mean',
                         'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:select_rates:score_func': 'chi2',
                         'classifier:passive_aggressive:C': 5.741307665645392,
                         'classifier:__choice__': 'passive_aggressive', 'preprocessor:__choice__': 'select_rates',
                         'preprocessor:select_rates:alpha': 0.1,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.3232447497379641e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                         'imputation:strategy': 'median', 'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1',
                         'classifier:passive_aggressive:C': 1.0,
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'passive_aggressive',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'preprocessor:liblinear_svc_preprocessor:C': 0.4971515945303584,
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.001856820833094005,
                         'preprocessor:liblinear_svc_preprocessor:tol': 1.932660215945159e-05,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.3232447497379641e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True', 'imputation:strategy': 'mean',
                         'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1',
                         'classifier:passive_aggressive:C': 1.0,
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'passive_aggressive',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'preprocessor:liblinear_svc_preprocessor:C': 0.4971515945303584,
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.001856820833094005,
                         'preprocessor:liblinear_svc_preprocessor:tol': 0.00010268311046018636,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.3232447497379641e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                         'imputation:strategy': 'median', 'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1',
                         'classifier:passive_aggressive:C': 0.8868625112793715,
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'passive_aggressive',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'preprocessor:liblinear_svc_preprocessor:C': 0.49590374754953515,
                         'preprocessor:liblinear_svc_preprocessor:tol': 3.25264424936244e-05,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.4400723753483714e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'classifier:liblinear_svc:dual': 'False', 'imputation:strategy': 'median',
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:tol': 0.00010268311046018636,
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'liblinear_svc',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'classifier:liblinear_svc:multi_class': 'ovr', 'classifier:liblinear_svc:intercept_scaling': 1,
                         'rescaling:__choice__': 'none', 'classifier:liblinear_svc:tol': 0.00010000000000000009,
                         'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'none',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1', 'classifier:liblinear_svc:C': 1.0,
                         'classifier:liblinear_svc:penalty': 'l2',
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'classifier:liblinear_svc:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:C': 0.4971515945303584,
                         'classifier:liblinear_svc:fit_intercept': 'True',
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr'},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'imputation:strategy': 'mean', 'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'classifier:passive_aggressive:C': 5.741307665645392,
                         'classifier:__choice__': 'passive_aggressive', 'preprocessor:__choice__': 'no_preprocessing',
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.3232447497379641e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:select_rates:mode': 'fpr', 'imputation:strategy': 'most_frequent',
                         'classifier:passive_aggressive:average': 'False',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'preprocessor:select_rates:score_func': 'chi2', 'classifier:passive_aggressive:C': 1.0,
                         'classifier:__choice__': 'passive_aggressive', 'preprocessor:__choice__': 'select_rates',
                         'preprocessor:select_rates:alpha': 0.1,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
                         'rescaling:__choice__': 'none', 'classifier:passive_aggressive:loss': 'hinge',
                         'classifier:passive_aggressive:tol': 1.3232447497379641e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'classifier:liblinear_svc:dual': 'False', 'imputation:strategy': 'median',
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.010000000000000004,
                         'preprocessor:liblinear_svc_preprocessor:intercept_scaling': 1,
                         'preprocessor:liblinear_svc_preprocessor:tol': 0.00010268311046018636,
                         'preprocessor:liblinear_svc_preprocessor:dual': 'False',
                         'classifier:__choice__': 'liblinear_svc',
                         'preprocessor:__choice__': 'liblinear_svc_preprocessor',
                         'classifier:liblinear_svc:multi_class': 'ovr', 'classifier:liblinear_svc:intercept_scaling': 1,
                         'rescaling:__choice__': 'normalize', 'classifier:liblinear_svc:tol': 0.00010000000000000009,
                         'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'preprocessor:liblinear_svc_preprocessor:fit_intercept': 'True',
                         'preprocessor:liblinear_svc_preprocessor:penalty': 'l1', 'classifier:liblinear_svc:C': 1.0,
                         'classifier:liblinear_svc:penalty': 'l2',
                         'preprocessor:liblinear_svc_preprocessor:loss': 'squared_hinge',
                         'classifier:liblinear_svc:loss': 'squared_hinge',
                         'preprocessor:liblinear_svc_preprocessor:C': 0.4971515945303584,
                         'classifier:liblinear_svc:fit_intercept': 'True',
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'preprocessor:liblinear_svc_preprocessor:multi_class': 'ovr'},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'weighting',
                         'imputation:strategy': 'median', 'classifier:passive_aggressive:average': 'True',
                         'classifier:passive_aggressive:fit_intercept': 'True',
                         'classifier:passive_aggressive:C': 0.0013048685612526427,
                         'classifier:__choice__': 'passive_aggressive', 'preprocessor:__choice__': 'no_preprocessing',
                         'categorical_encoding:one_hot_encoding:minimum_fraction': 0.010000000000000004,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'rescaling:__choice__': 'normalize', 'classifier:passive_aggressive:loss': 'squared_hinge',
                         'classifier:passive_aggressive:tol': 1.3258146886140332e-05},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    (0.020000, SimpleClassificationPipeline(
                        {'categorical_encoding:__choice__': 'one_hot_encoding', 'balancing:strategy': 'none',
                         'imputation:strategy': 'mean', 'categorical_encoding:one_hot_encoding:minimum_fraction': 0.01,
                         'classifier:random_forest:n_estimators': 100, 'classifier:random_forest:min_samples_leaf': 1,
                         'classifier:random_forest:criterion': 'gini', 'classifier:random_forest:bootstrap': 'True',
                         'classifier:random_forest:min_weight_fraction_leaf': 0.0,
                         'classifier:__choice__': 'random_forest', 'preprocessor:__choice__': 'no_preprocessing',
                         'classifier:random_forest:max_leaf_nodes': 'None',
                         'classifier:random_forest:min_impurity_decrease': 0.0,
                         'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
                         'classifier:random_forest:min_samples_split': 2, 'rescaling:__choice__': 'standardize',
                         'classifier:random_forest:max_features': 0.5, 'classifier:random_forest:max_depth': 'None'},
                        dataset_properties={
                            'task': 1,
                            'target_type': 'classification',
                            'multilabel': False,
                            'signed': False,
                            'sparse': True,
                            'multiclass': False})),
                    ]
